### ISSUE TITLE
Wrong size for extra data 

### ISSUE THREAD

**Issue by zhydong258** [flathub/com.jianguoyun.Nutstore#20]
Error: Wrong size for extra data https://pkg-cdn.jianguoyun.com/static/exe/installer/nutstore_linux_dist_x64.tar.gz
error: Failed to install com.jianguoyun.Nutstore: Wrong size for extra data https://pkg-cdn.jianguoyun.com/static/exe/installer/nutstore_linux_dist_x64.tar.gz

**Comment by zhydong258** [comment]
#24 使用这个方法倒是可以安装，目前来看，也能正常使用的。

**Comment by alexfanqi** [comment]
还是有这个问题，buildbot的链接也已经没了

**Comment by lnxyz** [comment]
> Error: Wrong size for extra data https://pkg-cdn.jianguoyun.com/static/exe/installer/nutstore_linux_dist_x64.tar.gz error: Failed to install com.jianguoyun.Nutstore: Wrong size for extra data https://pkg-cdn.jianguoyun.com/static/exe/installer/nutstore_linux_dist_x64.tar.gz

因为这个包更新了，所以 包大小 sha256sum 不一致了

**Comment by nuzar** [comment]
从 https://www.jianguoyun.com/static/exe/latestVersion?cache=false 能找到带版本信息的两个安装包，不是很确定 stUrl 和 exUrl 这两个包有什么区别，但是看压缩包目录结构和现在下载的 https://pkg-cdn.jianguoyun.com/static/exe/installer/nutstore_linux_dist_x64.tar.gz 是一致的。

```json
{
"OS": "linux-jdk7-x64",
"stVer": "6.3.0",
"stUrl": "https://dc-pkg-cdn.jianguoyun.com/static/exe/st/6.3.0/nutstore_client-6.3.0-linux-x86_64-public.tar.gz",
"exVer": "6.3.2",
"exUrl": "https://dc-pkg-cdn.jianguoyun.com/static/exe/ex/6.3.2/nutstore_client-6.3.2-linux-x86_64-public.tar.gz",
"exPercent": 4
}
```

@chenyuanrun 之前的下载链接是指向最新版本，厂家随时可能更新，导致校验失败。你觉得改成下载这个带版本的安装包如何？
